
disabled_rules:
  - identifier_name
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
custom_rules:
  override_func: # rule identifier
    name: "override in func" # rule name. optional.
    regex: "override (open|public|private|internal|fileprivate)" # matching pattern
    message: "Use like open override or public override instead" # violation message. optional.
    severity: warning # violation severity. optional.
included:
  - Sources