platform :ios, '9.0'

target 'ChatExample' do
  use_frameworks!
  pod 'MessageKit', :path => '../'
  pod 'MessageInputBar'

target 'ChatExampleTests' do
  inherit! :search_paths
end

target 'ChatExampleUITests' do
  inherit! :search_paths
end

end
