source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

target 'ChatExample' do
  use_frameworks!
  pod 'MessageKit', :path => '../'
  pod 'SwiftLint', '~> 0.40'
  pod 'PINRemoteImage', '~> 3.0.1', :subspecs => ['iOS', 'PINCache']

  target 'ChatExampleTests' do
    inherit! :search_paths
  end

  target 'ChatExampleUITests' do
    inherit! :search_paths
  end
end
