#!/bin/sh

if ! command -v swiftformat >/dev/null 2>&1; then
	echo "swiftformat not found. Install it with: brew install swiftformat"
	exit 1
fi

git diff --diff-filter=d --staged --name-only | grep -e '\(.*\).swift$' | while read line; do
	swiftformat "${line}";
  git add "$line";
done