name: Tests

on: pull_request

jobs:
  tests:
    name: Run Tests
    runs-on: macos-12
    env: 
       DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v2
    - name: Build and run tests
      run: make test
