name: Tests

on: pull_request

jobs:
  tests:
    name: Run Tests
    runs-on: macos-14
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v4
    - name: Build and run tests
      run: make test
