name: Tests

on: pull_request

jobs:
  tests:
    name: Run Tests
    runs-on: macOS-latest
    env: 
       DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v2
    - name: Build and run tests
      run: ./GitHubActions/build.sh tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.13

