name: Tests

on: pull_request

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  tests:
    name: Run Tests
    runs-on: macos-14
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v4
    - name: Build and run tests
      run: make test
